Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Metrics/BlockLength:
  Max: 35

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30
