name: Ruby

on: [push]

jobs:
  build:
    name: "Run Rspec Tests"
    env:
      PUPPET_GEM_VERSION: "~> 8.6.0"
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2]
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake spec
